//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrappedWPF.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BootstrappedWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Feel like you want to make a donation?  It would be gratefully received.  Click the button to donate via GitHub sponsors..
        /// </summary>
        public static string AboutTabItem_DonationText {
            get {
                return ResourceManager.GetString("AboutTabItem_DonationText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Say hello, make a feature request, or raise a bug through one of these channels:.
        /// </summary>
        public static string AboutTabItem_GetInTouchExtendedText {
            get {
                return ResourceManager.GetString("AboutTabItem_GetInTouchExtendedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get In Touch.
        /// </summary>
        public static string AboutTabItem_GetInTouchText {
            get {
                return ResourceManager.GetString("AboutTabItem_GetInTouchText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This project is completely open source. If you like it and want to say thanks you could hit the GitHub Star button, tweet or post about it, or tell your mum about it!.
        /// </summary>
        public static string AboutTabItem_OpenSourceExtendedText {
            get {
                return ResourceManager.GetString("AboutTabItem_OpenSourceExtendedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Source.
        /// </summary>
        public static string AboutTabItem_OpenSourceText {
            get {
                return ResourceManager.GetString("AboutTabItem_OpenSourceText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BootstrappedWPF.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string ChatCodes_SaveChangesText {
            get {
                return ResourceManager.GetString("ChatCodes_SaveChangesText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to Sharlayan&apos;s WPF Example.
        /// </summary>
        public static string HomeTabItem_WelcomeText {
            get {
                return ResourceManager.GetString("HomeTabItem_WelcomeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_AboutButtonText {
            get {
                return ResourceManager.GetString("MainWindow_AboutButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChatLog.
        /// </summary>
        public static string MainWindow_ChatLogButtonText {
            get {
                return ResourceManager.GetString("MainWindow_ChatLogButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string MainWindow_DebugButtonText {
            get {
                return ResourceManager.GetString("MainWindow_DebugButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainWindow_HomeButtonText {
            get {
                return ResourceManager.GetString("MainWindow_HomeButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_SettingsButtonText {
            get {
                return ResourceManager.GetString("MainWindow_SettingsButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string Palette_AccentText {
            get {
                return ResourceManager.GetString("Palette_AccentText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Palette_DarkText {
            get {
                return ResourceManager.GetString("Palette_DarkText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Palette_LightText {
            get {
                return ResourceManager.GetString("Palette_LightText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mid.
        /// </summary>
        public static string Palette_MidText {
            get {
                return ResourceManager.GetString("Palette_MidText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Primary - Mid.
        /// </summary>
        public static string Palette_PrimaryMidText {
            get {
                return ResourceManager.GetString("Palette_PrimaryMidText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string PaletteSelector_AccentText {
            get {
                return ResourceManager.GetString("PaletteSelector_AccentText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string PaletteSelector_DarkText {
            get {
                return ResourceManager.GetString("PaletteSelector_DarkText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is your current palette..
        /// </summary>
        public static string PaletteSelector_DescriptionText {
            get {
                return ResourceManager.GetString("PaletteSelector_DescriptionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string PaletteSelector_LightText {
            get {
                return ResourceManager.GetString("PaletteSelector_LightText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string PaletteSelector_PrimaryText {
            get {
                return ResourceManager.GetString("PaletteSelector_PrimaryText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chat Codes.
        /// </summary>
        public static string SettingsTabItem_ChatCodesTabHeaderText {
            get {
                return ResourceManager.GetString("SettingsTabItem_ChatCodesTabHeaderText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sharlayan.
        /// </summary>
        public static string SettingsTabItem_SharlayanTabHeaderText {
            get {
                return ResourceManager.GetString("SettingsTabItem_SharlayanTabHeaderText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsTabItem_ThemeTabHeaderText {
            get {
                return ResourceManager.GetString("SettingsTabItem_ThemeTabHeaderText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string UserSettings_ActionsHelperText {
            get {
                return ResourceManager.GetString("UserSettings_ActionsHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        public static string UserSettings_ActorHelperText {
            get {
                return ResourceManager.GetString("UserSettings_ActorHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adjust these timings to increase or decrease data latency. Faster timings may increase CPU usage..
        /// </summary>
        public static string UserSettings_AdjustmentText {
            get {
                return ResourceManager.GetString("UserSettings_AdjustmentText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChatLog.
        /// </summary>
        public static string UserSettings_ChatLogHelperText {
            get {
                return ResourceManager.GetString("UserSettings_ChatLogHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current Player.
        /// </summary>
        public static string UserSettings_CurrentPlayerHelperText {
            get {
                return ResourceManager.GetString("UserSettings_CurrentPlayerHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Settings.
        /// </summary>
        public static string UserSettings_DataSettingsText {
            get {
                return ResourceManager.GetString("UserSettings_DataSettingsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string UserSettings_InventoryHelperText {
            get {
                return ResourceManager.GetString("UserSettings_InventoryHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Job Resources.
        /// </summary>
        public static string UserSettings_JobResourcesHelperText {
            get {
                return ResourceManager.GetString("UserSettings_JobResourcesHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory Timings.
        /// </summary>
        public static string UserSettings_MemoryTimingsText {
            get {
                return ResourceManager.GetString("UserSettings_MemoryTimingsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Party Members.
        /// </summary>
        public static string UserSettings_PartyMembersHelperText {
            get {
                return ResourceManager.GetString("UserSettings_PartyMembersHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string UserSettings_ResetSettingsText {
            get {
                return ResourceManager.GetString("UserSettings_ResetSettingsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string UserSettings_TargetHelperText {
            get {
                return ResourceManager.GetString("UserSettings_TargetHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use locally cached JSON for Sharlayan resources.
        /// </summary>
        public static string UserSettings_UseCachedDataText {
            get {
                return ResourceManager.GetString("UserSettings_UseCachedDataText", resourceCulture);
            }
        }
    }
}
